language: node_js
node_js:
  - lts/*
install:
  - yarn
before_deploy: 'yarn build'
deploy:
  provider: npm
  email: cqzhengmouren@gmail.com
  api_key: '$NPM_TOKEN'
  on:
    tags: true
    repo: jaluik/wx-ci
  skip_cleanup: 'true'
